/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiUnreadRouteImport } from './routes/api/unread'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiDevLoginRouteImport } from './routes/api/dev-login'
import { Route as ApiCreatorsRouteImport } from './routes/api/creators'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedMessagesRouteImport } from './routes/_protected/messages'
import { Route as ProtectedMeRouteImport } from './routes/_protected/me'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCreatorsRouteImport } from './routes/_protected/creators'
import { Route as ProtectedAboutRouteImport } from './routes/_protected/about'
import { Route as ApiCreatorsUsernameRouteImport } from './routes/api/creators.$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiConversationsIdRefundRouteImport } from './routes/api/conversations.$id.refund'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations.$id.messages'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnreadRoute = ApiUnreadRouteImport.update({
  id: '/api/unread',
  path: '/api/unread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevLoginRoute = ApiDevLoginRouteImport.update({
  id: '/api/dev-login',
  path: '/api/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatorsRoute = ApiCreatorsRouteImport.update({
  id: '/api/creators',
  path: '/api/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMessagesRoute = ProtectedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMeRoute = ProtectedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCreatorsRoute = ProtectedCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiCreatorsUsernameRoute = ApiCreatorsUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ApiCreatorsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdRefundRoute =
  ApiConversationsIdRefundRouteImport.update({
    id: '/$id/refund',
    path: '/$id/refund',
    getParentRoute: () => ApiConversationsRoute,
  } as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/$id/messages',
    path: '/$id/messages',
    getParentRoute: () => ApiConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/about': typeof ProtectedAboutRoute
  '/creators': typeof ProtectedCreatorsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/me': typeof ProtectedMeRoute
  '/messages': typeof ProtectedMessagesRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/creators': typeof ApiCreatorsRouteWithChildren
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/me': typeof ApiMeRoute
  '/api/ping': typeof ApiPingRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/unread': typeof ApiUnreadRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creators/$username': typeof ApiCreatorsUsernameRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/refund': typeof ApiConversationsIdRefundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/about': typeof ProtectedAboutRoute
  '/creators': typeof ProtectedCreatorsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/me': typeof ProtectedMeRoute
  '/messages': typeof ProtectedMessagesRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/creators': typeof ApiCreatorsRouteWithChildren
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/me': typeof ApiMeRoute
  '/api/ping': typeof ApiPingRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/unread': typeof ApiUnreadRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creators/$username': typeof ApiCreatorsUsernameRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/refund': typeof ApiConversationsIdRefundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/_protected/about': typeof ProtectedAboutRoute
  '/_protected/creators': typeof ProtectedCreatorsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/me': typeof ProtectedMeRoute
  '/_protected/messages': typeof ProtectedMessagesRoute
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/creators': typeof ApiCreatorsRouteWithChildren
  '/api/dev-login': typeof ApiDevLoginRoute
  '/api/me': typeof ApiMeRoute
  '/api/ping': typeof ApiPingRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/unread': typeof ApiUnreadRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creators/$username': typeof ApiCreatorsUsernameRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/refund': typeof ApiConversationsIdRefundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/about'
    | '/creators'
    | '/dashboard'
    | '/me'
    | '/messages'
    | '/onboarding'
    | '/api/conversations'
    | '/api/creators'
    | '/api/dev-login'
    | '/api/me'
    | '/api/ping'
    | '/api/stats'
    | '/api/unread'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/profile/$username'
    | '/api/auth/$'
    | '/api/creators/$username'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/refund'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/about'
    | '/creators'
    | '/dashboard'
    | '/me'
    | '/messages'
    | '/onboarding'
    | '/api/conversations'
    | '/api/creators'
    | '/api/dev-login'
    | '/api/me'
    | '/api/ping'
    | '/api/stats'
    | '/api/unread'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/profile/$username'
    | '/api/auth/$'
    | '/api/creators/$username'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/refund'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/landing'
    | '/login'
    | '/_protected/about'
    | '/_protected/creators'
    | '/_protected/dashboard'
    | '/_protected/me'
    | '/_protected/messages'
    | '/_protected/onboarding'
    | '/api/conversations'
    | '/api/creators'
    | '/api/dev-login'
    | '/api/me'
    | '/api/ping'
    | '/api/stats'
    | '/api/unread'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/profile/$username'
    | '/api/auth/$'
    | '/api/creators/$username'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/refund'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiCreatorsRoute: typeof ApiCreatorsRouteWithChildren
  ApiDevLoginRoute: typeof ApiDevLoginRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiUnreadRoute: typeof ApiUnreadRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unread': {
      id: '/api/unread'
      path: '/api/unread'
      fullPath: '/api/unread'
      preLoaderRoute: typeof ApiUnreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-login': {
      id: '/api/dev-login'
      path: '/api/dev-login'
      fullPath: '/api/dev-login'
      preLoaderRoute: typeof ApiDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creators': {
      id: '/api/creators'
      path: '/api/creators'
      fullPath: '/api/creators'
      preLoaderRoute: typeof ApiCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/messages': {
      id: '/_protected/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ProtectedMessagesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/me': {
      id: '/_protected/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof ProtectedMeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/creators': {
      id: '/_protected/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof ProtectedCreatorsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/about': {
      id: '/_protected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedAboutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/creators/$username': {
      id: '/api/creators/$username'
      path: '/$username'
      fullPath: '/api/creators/$username'
      preLoaderRoute: typeof ApiCreatorsUsernameRouteImport
      parentRoute: typeof ApiCreatorsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/refund': {
      id: '/api/conversations/$id/refund'
      path: '/$id/refund'
      fullPath: '/api/conversations/$id/refund'
      preLoaderRoute: typeof ApiConversationsIdRefundRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAboutRoute: typeof ProtectedAboutRoute
  ProtectedCreatorsRoute: typeof ProtectedCreatorsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMeRoute: typeof ProtectedMeRoute
  ProtectedMessagesRoute: typeof ProtectedMessagesRoute
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedCreatorsRoute: ProtectedCreatorsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMeRoute: ProtectedMeRoute,
  ProtectedMessagesRoute: ProtectedMessagesRoute,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiConversationsRouteChildren {
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
  ApiConversationsIdRefundRoute: typeof ApiConversationsIdRefundRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
  ApiConversationsIdRefundRoute: ApiConversationsIdRefundRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

interface ApiCreatorsRouteChildren {
  ApiCreatorsUsernameRoute: typeof ApiCreatorsUsernameRoute
}

const ApiCreatorsRouteChildren: ApiCreatorsRouteChildren = {
  ApiCreatorsUsernameRoute: ApiCreatorsUsernameRoute,
}

const ApiCreatorsRouteWithChildren = ApiCreatorsRoute._addFileChildren(
  ApiCreatorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiCreatorsRoute: ApiCreatorsRouteWithChildren,
  ApiDevLoginRoute: ApiDevLoginRoute,
  ApiMeRoute: ApiMeRoute,
  ApiPingRoute: ApiPingRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiUnreadRoute: ApiUnreadRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
